site_name: Itiberê G.S. Filho
theme:
#  name: material
#  name: dracula
#  name: windmill
#  name: swan
  name: lux
  icon: fontawesome/solid/gun
plugins: 
  - d2
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - mdx_math

extra:
  generator: false

nav:
  - Sobre mim: index.md
  - Experiência:
    - Experiência Profissional: profissional.md
    - Experiência Acadêmica: academica.md
  - Estudos:
    - Certificações, Provas e Acreditações: certificacoes.md
    - Formações e Cursos: cursos.md
    - Artigos e Resumos Publicados: artigos.md
    - Projetos: projetos.md
    - Participações em Eventos: eventos.md
  - Curriculo Compacto: compacto.html